class Assingment25{
    public static void main(String args[]){
        float num1 = 129;
        Float num = new Float(num1);
        System.out.println(num.byteValue());
        System.out.println(num.shortValue());
        System.out.println(num.intValue());
        System.out.println(num.floatValue());
        System.out.println(num.doubleValue());
        System.out.println(num.longValue());
    }
}